In [8]:
def rotate(Matrix):
    n = len(Matrix)
    for i in range(n // 2):
        for j in range((n + 1) // 2):
            temp = Matrix[i][j]
            Matrix[i][j] = Matrix[n-j-1][i]
            Matrix[n-j-1][i] = Matrix[n-i-1][n-j-1]
            Matrix[n-i-1][n-j-1] = Matrix[j][n-i-1]
            Matrix[j][n-i-1] = temp
    return Matrix

In [9]:
import numpy as np

In [10]:
M = np.random.random([4,4])
print(M)
res = rotate(M)
print(res)

[[0.39357204 0.6419659  0.93364583 0.01690716]
 [0.15948077 0.22327587 0.32834905 0.33067363]
 [0.09052863 0.14961077 0.18260712 0.49254781]
 [0.72025876 0.88713025 0.63383126 0.25944669]]
[[0.72025876 0.09052863 0.15948077 0.39357204]
 [0.88713025 0.14961077 0.22327587 0.6419659 ]
 [0.63383126 0.18260712 0.32834905 0.93364583]
 [0.25944669 0.49254781 0.33067363 0.01690716]]
