In [3]:
def setZeros(Matrix):
    rows = len(Matrix)
    cols = len(Matrix[0])
    row_label = [False for _ in range(rows)]
    col_label = [False for _ in range(cols)]
    for i in range(rows):
        for j in range(cols):
            if(Matrix[i][j] == 0):
                row_label[i] = True
                col_label[j] = True
    
    for i in range(rows):
        for j in range(cols):
            if(row_label[i] or col_label[j]):
                Matrix[i][j] = 0
                
    return Matrix

In [4]:
import numpy as np

In [5]:
M = np.random.random([5,5])
M[4][0] = M[2][3] = 0
print(M)
res = setZeros(M)
print(res)

[[0.35059447 0.51739632 0.12068562 0.76607601 0.65408101]
 [0.81260914 0.16406393 0.63667167 0.39720145 0.60101946]
 [0.29239084 0.73704132 0.91517465 0.         0.47367747]
 [0.88430263 0.49118348 0.51537895 0.55026767 0.96101903]
 [0.         0.01009122 0.48488703 0.56136699 0.32638921]]
[[0.         0.51739632 0.12068562 0.         0.65408101]
 [0.         0.16406393 0.63667167 0.         0.60101946]
 [0.         0.         0.         0.         0.        ]
 [0.         0.49118348 0.51537895 0.         0.96101903]
 [0.         0.         0.         0.         0.        ]]
